# Generated by Django 5.2.3 on 2025-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('acne_prone', 'Acne-Prone')], max_length=20, null=True),
        ),
    ]
