# Generated by Django 5.2.3 on 2025-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
