# Generated by Django 5.2.3 on 2025-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image_alter_profile_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Dry', 'Dry'), ('Oily', 'Oily'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive'), ('Acne-prone', 'Acne-prone')], max_length=50, null=True),
        ),
    ]
